name: Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push image to ACR
      uses: azure/docker-login@v1
      with:
        login-server: passcountacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build -t passcountacr.azurecr.io/passenger-counting-system:${{ github.sha }} .
        docker push passcountacr.azurecr.io/passenger-counting-system:${{ github.sha }}
    
    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: passenger-counting-rg
        cluster-name: passenger-counting-aks
    
    - name: Update deployment image
      run: |
        kubectl set image deployment/passenger-counting-system passenger-counting-system=passcountacr.azurecr.io/passenger-counting-system:${{ github.sha }}
